apiVersion: apps/v1
kind: Deployment
metadata:
  name: odh-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: odh-dashboard
  template:
    metadata:
      labels:
        deployment: odh-dashboard
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - odh-dashboard
                topologyKey: topology.kubernetes.io/zone
      serviceAccount: odh-dashboard
      containers:
      - name: odh-dashboard
        image: odh-dashboard    # Replaced by the kustomize images parameter
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /api/status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 15
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 15
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
