kind: ServiceAccount
apiVersion: v1
metadata:
  name: odh-dashboard
  # Manually specifying the namespace will force kustomize to transform the
  #  namespace for all Cluster)RoleBindings referencing this ServiceAccount
  namespace: odh-dashboard
